// // <copyright file="SettingsData.cs" company="PublicDomain.com">
// //     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
// //     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// // </copyright>
// // <auto-generated />

namespace PublicDomain
{
    // Directives
    using System.Collections.Generic;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> always on top.
        /// </summary>
        /// <value><c>true</c> if always on top; otherwise, <c>false</c>.</value>
        public bool AlwaysOnTop { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> minimize on loop start.
        /// </summary>
        /// <value><c>true</c> if minimize on loop start; otherwise, <c>false</c>.</value>
        public bool MinimizeOnLoopStart { get; set; } = false;

        /// <summary>
        /// Gets or sets the key.
        /// </summary>
        /// <value>The key.</value>
        public string Key { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the presses.
        /// </summary>
        /// <value>The presses.</value>
        public decimal Presses { get; set; } = 1;

        /// <summary>
        /// TODO Gets or sets the interval. [Can be made an integer, for int.TryParse()]
        /// </summary>
        /// <value>The interval.</value>
        public string Interval { get; set; } = "1000";
    }
}